OBJs =  main.o

sticks: $(OBJs)
	g++ -Wall -g $(OBJs) -o sticks 


#Queue.o: Queue.c Queue.h Stack.h
#	gcc -Wall -g -c  Queue.c

clean:
	rm -f *.o
	rm -fr heapsort.dSYM

run:	clean sticks 
	#./sticks
